Add callback url option to fix regression for OAuth2 1.4
nashby/omniauth-stackexchange pull request #8
Opened 2016-11-19 12:25 UTC by gauravtiwari

* Update old ruby syntax
* Fixes regression in omniauth-oauth2 v1.4.0 by intridea/omniauth-oauth2@85fdbe1 
* Update readme

2016-11-19 12:26 UTC, gauravtiwari commented
@nashby Please review and publish a new version to ruby gems :)

2016-11-19 12:33 UTC, gauravtiwari commented
Looks like travis is having a bad day

2016-11-20 16:57 UTC, nashby requested changes

2016-11-20 16:57 UTC, nashby commented on CHANGELOG.md
> +## 0.2.1 (September 22, 2015) ##
looks like you copy-pasted version as well here :) 
Can you just put that README addition to the `## Unreleased` section?

2016-11-20 16:57 UTC, nashby commented
@gauravtiwari hey, thanks for PR!

2016-11-26 13:06 UTC, merged

2016-11-26 13:06 UTC, nashby commented
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

2016-11-27 05:49 UTC, gauravtiwari commented
Hey, totally forgot about this. Awesome ❤️